server:
  port: 6003
spring:
  application:
    name: e-toll-driver-profile-service
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: admin
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/uaa/user
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG

